[package]
name = "ferrisume-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ferrisume-core = { path = "../ferrisume-core" }
clap = "2.33"
log = "0.4.22"
serde_json = "1.0.120"
env_logger = "0.11.4"
tiny_http = "0.12.0"
notify = "6.1.1"
ws = "0.9.2"
