[package]
name = "ferrisume-cli"
description = "A JSON resume CLI tool"
version = "0.6.1"
license = "MIT"
repository = "https://github.com/van-sprundel/ferrisume"
edition = "2021"
keywords = ["cli", "json", "resume"]
categories = ["visualization", "value-formatting"]

include = ["/src", "themes/default/**"]

[dependencies]
clap = { version = "4.5.12" }
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.120"
env_logger = "0.11.4"
tiny_http = "0.12.0"
notify = "6.1.1"
handlebars = "6.0.0"
anyhow = "1.0"
thiserror = "1.0"
toml = "0.8.15"
headless_chrome = { version = "1.0.15", features = ["fetch"] }
tempfile = "3.12.0"
directories = "6.0.0"
lazy_static = "1.4.0"
comfy-table = "7.1.4"
self_update = { version = "1.0.0-rc.6", features = ["archive-zip", "compression-zip-deflate", "checksums"] }
clap_complete = "4"
jsonschema = { version = "0.47.0", default-features = false }

[[bin]]
name = "ferrisume"
path = "src/main.rs"

# The profile that 'dist' will use to build the release
[profile.dist]
inherits = "release"
lto = "thin"

[dev-dependencies]
flate2 = "1.1.9"
tar = "0.4.46"
