[package]
name = "ferrisume-domain"
description = "The domain entities for the ferrisume CLI tool"
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/yourusername/ferrisume"

[dependencies]
serde = { version = "1", features = ["derive"] }
